"""Streamlit UI application."""

import streamlit as st
from datetime import datetime
from uuid import uuid4

from reportagent.schemas import ChatState, MessageRole
from reportagent.graphs.chat import chat_graph
from reportagent.storage.archive import Archive
from reportagent.observability.logging import setup_logging
from reportagent.observability.tracing import setup_tracing

# Setup
setup_logging()
setup_tracing()

st.set_page_config(
    page_title="UK AI Regulation Intelligence Agent",
    page_icon="📰",
    layout="wide",
)

# Header
st.title("📰 UK AI Regulation Intelligence Agent")
st.markdown("Powered by LangGraph + Claude AI")

# Initialize session state
if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid4())

if "messages" not in st.session_state:
    st.session_state.messages = []

# Sidebar
with st.sidebar:
    st.header("📊 System Status")

    # Get archive stats
    try:
        archive = Archive()
        latest_report = archive.get_latest_report("uk_ai_regulation")
        latest_run = archive.get_latest_run_log()

        if latest_report:
            st.subheader("Latest Report")
            st.markdown(f"**Generated:** {latest_report.generated_at.strftime('%Y-%m-%d %H:%M')}")
            st.markdown(f"**Summary:**\n{latest_report.summary[:200]}...")

            with st.expander("📌 Key Takeaways"):
                for takeaway in latest_report.key_takeaways:
                    st.markdown(f"• {takeaway}")

        if latest_run:
            st.markdown(f"**Last Run Status:** {'✅ Success' if latest_run.status.value == 'success' else '❌ Failed'}")
            st.markdown(f"**Articles Fetched:** {latest_run.articles_fetched}")
            st.markdown(f"**Chunks Added:** {latest_run.chunks_added}")

    except Exception as e:
        st.error(f"Error loading system status: {str(e)}")

    # Trigger button
    if st.button("🚀 Trigger Ingestion Now"):
        with st.spinner("Running ingestion..."):
            try:
                from reportagent.schemas import IngestionState
                from reportagent.graphs.ingestion import ingestion_graph

                state = IngestionState(
                    run_id=str(uuid4()),
                    topic="uk_ai_regulation",
                )
                ingestion_graph.invoke(state.model_dump())
                st.success("Ingestion completed!")

            except Exception as e:
                st.error(f"Ingestion failed: {str(e)}")

# Main chat area
st.header("💬 Ask a Question")

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message.role.value):
        st.write(message.content)
        if message.citations:
            with st.expander("📚 Sources"):
                for citation in message.citations:
                    st.markdown(f"[[{citation.index}] {citation.url}]({citation.url})")

# Chat input
user_input = st.chat_input("Ask a question about UK AI regulation...")

if user_input:
    # Add user message to history
    from reportagent.schemas import ChatMessage
    user_message = ChatMessage(
        role=MessageRole.USER,
        content=user_input,
    )
    st.session_state.messages.append(user_message)

    # Display user message
    with st.chat_message("user"):
        st.write(user_input)

    # Generate response
    with st.spinner("Thinking..."):
        try:
            chat_state = ChatState(
                session_id=st.session_state.session_id,
                current_query=user_input,
            )

            result = chat_graph.invoke(chat_state.model_dump())

            if result.get("response"):
                response_msg = ChatMessage.model_validate(result["response"])
                st.session_state.messages.append(response_msg)

                # Display assistant response
                with st.chat_message("assistant"):
                    st.write(response_msg.content)

                    if response_msg.citations:
                        with st.expander("📚 Sources"):
                            for citation in response_msg.citations:
                                st.markdown(f"[[{citation.index}] {citation.url}]({citation.url})")

        except Exception as e:
            st.error(f"Error generating response: {str(e)}")

# Footer
st.markdown("---")
st.markdown(
    """
    <div style="text-align: center; color: gray; font-size: 0.8em;">
    Generated by Data Reply GenAI Agent • Session: {}</div>
    """.format(st.session_state.session_id[:8]),
    unsafe_allow_html=True,
)
